### ISSUE TITLE
Zip archive for release contains folder

### ISSUE THREAD

**Issue by ianrathbone** [ianrathbone/microsoft-teams-together-scene-muppets#5]
The archive should instead be a flat file with the three items needed by the development studio

**Comment by ianrathbone** [comment]
Fixed in latest alpha

**Comment by marc-flywheel** [comment]
You may want to make a new release incorporating this because your 1.0 release has the /scenefiles/ directory in the zip which prevents the import into the Teams Dev site.

**Comment by ianrathbone** [comment]
@marc-flywheel thanks for this - honestly thought I had fixed this last night when I made the new release!! 🤭

**Comment by ianrathbone** [comment]
Fixed with releases/tag/v1.1
